version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: yes